version: "3.5"
services:
  gmod-server:
    image: massimilianopasquini/gmod-server:latest
    container_name: gmod-terrortown-server
    restart: on-failure
    volumes:
      - type: volume
        source: gamefolder-gmod-terrortown-server
        target: /home/gmod/gmod-server
    environment:
      Server_Name: '[terrortown]Server'
      Server_Max_Player: '20'
      Server_Gmod_Mod: 'terrortown'
      Server_workshop_collection: '1649752447'
      Server_Map: 'ttt_island_2013'
    ports:
      - target: 27015
        published: 27015
        protocol: udp
        mode: host
      - target: 27005
        published: 27005
        protocol: udp
        mode: host
volumes:
  gamefolder-gmod-terrortown-server: