version: "3.5"
services:
  gmod-server:
    image: massimilianopasquini/gmod-server:latest
    container_name: gmod-psw2-server
    restart: on-failure
    volumes:
      - type: volume
        source: gamefolder-gmod-psw2-server
        target: /home/gmod/gmod-server
    environment:
      Server_Name: '[Pirate Ship War 2]Server'
      Server_Max_Player: '20'
      Server_Gmod_Mod: 'psw2'
      Server_workshop_collection: '648145510'
      Server_Map: 'pw_ocean_day'
    ports:
      - target: 27015
        published: 27015
        protocol: udp
        mode: host
      - target: 27005
        published: 27005
        protocol: udp
        mode: host
volumes:
  gamefolder-gmod-psw2-server: