version: "3.5"
services:
  gmod-server:
    image: massimilianopasquini/gmod-server:latest
    container_name: gmod-prophunt-server
    restart: on-failure
    volumes:
      - type: volume
        source: gamefolder-gmod-prophunt-server
        target: /home/gmod/gmod-server
    environment:
      Server_Name: '[Prop Hunt]Server'
      Server_Max_Player: '20'
      Server_Gmod_Mod: 'prop_hunt'
      Server_workshop_collection: '1648902801'
      Server_Map: 'ph_infernaria'
    ports:
      - target: 27015
        published: 27015
        protocol: udp
        mode: host
      - target: 27005
        published: 27005
        protocol: udp
        mode: host
volumes:
  gamefolder-gmod-prophunt-server: